# Generated by Django 3.0.2 on 2021-05-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0004_auto_20210527_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answerMark',
            field=models.IntegerField(default=0),
        ),
    ]
