# Generated by Django 3.0.2 on 2021-06-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0011_delete_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiztaker',
            old_name='marks',
            new_name='score',
        ),
    ]
