# Generated by Django 3.0.2 on 2021-06-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0013_auto_20210602_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quizMarks',
            field=models.FloatField(default=10),
        ),
    ]
