# Generated by Django 3.0.2 on 2021-06-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0014_quiz_quizmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quizMarks',
            new_name='quizScore',
        ),
    ]
